Update phpunit/phpunit and illuminate/database
ranium/laravel-seedonce pull request #22
Opened 2024-04-02 10:46 UTC by alexweb

2024-04-08 04:43 UTC, abbasali commented
@alexweb One of the tests is failing. Can you please fix that test? Also would appreciate it if you could add a test for Laravel 11 and PHP 8.2 and 8.3.

2024-04-09 09:44 UTC, alexweb commented
> @alexweb One of the tests is failing. Can you please fix that test? Also would appreciate it if you could add a test for Laravel 11 and PHP 8.2 and 8.3.

Hmm... Not sure I know how to do that in Github. I just run `composer test` locally and tests pass.
Do you know how to add/change the tests you mentioned?

2024-04-09 10:12 UTC, abbasali commented
@alexweb you need to do a couple of things in `.github/workflows/tests.yml` file
1. Add new PHP and laravel versions on line 14 and 15 (matrix)
2. Remove `--verbose` from the `vendor/bin/phpunit --verbose --testdox` command on line 36.

Can you please update the PR with these changes?

2024-04-09 10:53 UTC, abbasali requested changes

2024-04-09 11:29 UTC, merged